#FROM nginx:1.27.4-alpine
#COPY ./modules/alpine.ngx_curity_http_phantom_token_module_1.27.4.so /usr/lib/nginx/modules/ngx_curity_http_phantom_token_module.so

FROM nginx:1.29.5-alpine
COPY ./modules/alpine.ngx_curity_http_phantom_token_module_1.29.5.so /usr/lib/nginx/modules/ngx_curity_http_phantom_token_module.so